### ISSUE TITLE
Plugin Enhancement

### ISSUE THREAD

**Issue by WatchTheory** [fow5040/Flow.Launcher.Plugin.SpotifyPremium#1]
It would be great to see if you can go into the playlist and play songs through Flow Launcher.
For example 

typing "Spotify" then typing "playlist" then being able to open the playlist to play a song.

**Comment by fow5040** [comment]
This is a good idea - it will require a bit more of a mature framework to have 'actionable' items, but will keep it in mind in the future

Currently, the idea is when you hit enter, the flow workflow stops and the action is done - if you have context sensitive actions (i.e. hit enter on a playlist to return more results and browse the playlist) it changes the desired workflow and requires more context sensitive Wox Results. I'll think about a better system to put this in place

**Comment by WatchTheory** [comment]
I used this flow about more than any other flow out there. It helps me start and stop my Spotify, if I was a better programmer I would help get this flow up to date. I appreciate the work that goes into keeping this flow available for everyone. @ @
