### ISSUE TITLE
Request: Adding a volume change contextual option. E.g. `sp vol +20`

### ISSUE THREAD

**Issue by dharrison27** [fow5040/Flow.Launcher.Plugin.SpotifyPremium#13]
### Issue Description

N/a. Not an issue but a feature suggestion/request

### Functionality Affected

Please mark the functionality of the plugin that is affected by the issue:

- [X] Controlling the local Spotify client (changing track, pausing, skipping, muting)
- [ ] Searching Spotify for albums, artists or songs

### Software Versions

Please fill in the following information:

- Spotify client version (`Help > About Spotify`): Spotify for Windows 1.1.96.785.g464c973a
- Flow Launcher version (`Flow Settings > About`): 1.9.5

**Please also make sure you're running the latest version of Flow.Launcher.Plugin.SpotifyPremium**

That's it, really. A suggestion. I hope I filed this correctly. Thank you for a fantastic plug-in for flow launcher. Love and use it daily.

**Comment by fow5040** [comment]
Good suggestion! This wasn't too hard to add, I'll build it and get it updated in flow PM soon :)

**Comment by fow5040** [comment]
Added in commit 555722edd8aa30286598f6bb87ec5c682995ed46

Released in v1.1.3

**Comment by dharrison27** [comment]
@fow5040 very cool, thank you!!! 
Impressed.

**Comment by dharrison27** [comment]
...and just like that it broke! :(

**Comment by fow5040** [comment]
I think the volume API changed - even when I try through the developer console I get:
```
{
  "error": {
    "status": 403,
    "message": "Player command failed: Cannot control device volume",
    "reason": "VOLUME_CONTROL_DISALLOW"
  }
}
```

https://developer.spotify.com/console/put-volume/?volume_percent=&device_id=

They may have changed their API settings, I'll need to take a closer look later this week.

**Comment by fow5040** [comment]
See Issue #16
