### ISSUE TITLE
Typo in latest release tag

### ISSUE THREAD

**Issue by Garulf** [fow5040/Flow.Launcher.Plugin.SpotifyPremium#15]
Hello @fow5040 ,

I noticed the CI for Flow Launcher's auto-update workflow has been crashing due to a typo in your latest release's tag. Currently it is assigned `v.1.1.3`. It *should* be `v1.1.3`.

The crash has been resolved with the manifest, however the CI will skip any plugin that causes exceptions like described. Once the typo is fixed the manifest will pick up releases like normal.

**Comment by fow5040** [comment]
Thanks for catching this, I'll go ahead and update the release tag. Sorry for the downstream issues!

**Comment by fow5040** [comment]
Updated the Release Tag

**Comment by Garulf** [comment]
> Thanks for catching this, I'll go ahead and update the release tag. Sorry for the downstream issues!

All good! If anything you helped find a nasty bug ^_^
