### ISSUE TITLE
Volume Control Permission 403 Forbidden

### ISSUE THREAD

**Issue by fow5040** [fow5040/Flow.Launcher.Plugin.SpotifyPremium#16]
### Issue Description

I think the volume API changed - changing volume (even through the developer console) returns this error:
```
{
  "error": {
    "status": 403,
    "message": "Player command failed: Cannot control device volume",
    "reason": "VOLUME_CONTROL_DISALLOW"
  }
}
```
https://developer.spotify.com/console/put-volume/?volume_percent=&device_id=

They may have changed their API settings, I'll need to take a closer look later this week.

### Functionality Affected

Please mark the functionality of the plugin that is affected by the issue:

- [x] Controlling the local Spotify client (changing track, pausing, skipping, muting)
- [ ] Searching Spotify for albums, artists or songs

### Software Versions

Please fill in the following information:

- Spotify client version (`Help > About Spotify`): latest
- Flow Launcher version (`Flow Settings > About`): latest

**Comment by fow5040** [comment]
@dharrison27

**Comment by fow5040** [comment]
I think this was a transient issue with Spotify's API - it's not happening anymore on my client.

**Comment by dharrison27** [comment]
Tested, works for me :)

Thanks again for all the free and amazing work you put in to make amazing tools such as this, @fow5040 <3
