### ISSUE TITLE
Unable to Authorize with Spotify

### ISSUE THREAD

**Issue by Crossbones18** [fow5040/Flow.Launcher.Plugin.SpotifyPremium#6]
### Issue Description

Unable to Authorize Plugin. Downloaded plugin, created the app in developer Spotify. Setup Security.Store file with Client ID and secret. Setup URI. 

Then, when going into Flow, it tells me that the client needs to be authorized. Nothing happens when I click on it. I go to no webpage to authorize the application. 

### Functionality Affected

Please mark the functionality of the plugin that is affected by the issue:

- [X] Controlling the local Spotify client (changing track, pausing, skipping, muting)
- [X] Searching Spotify for albums, artists or songs

### Software Versions

Please fill in the following information:

- Spotify client version (`Help > About Spotify`): Spotify for Windows 1.1.79.763.gc2965cdf
- Flow Launcher version (`Flow Settings > About`): 1.9.2

**Please also make sure you're running the latest version of Flow.Launcher.Plugin.SpotifyPremium**

**Comment by fow5040** [comment]
Thanks for letting me know! Not sure what broke it but looking into it now.

**Comment by fow5040** [comment]
Looked into this - not sure exactly what's going on but I think the new version of Flow probably uses a different .NET runtime or something. I updated flow (`Flow` -> `Check for update`) and the spotify plugin is working fine. Does that resolve the issue?

**Comment by peterkx** [comment]
[Logs.zip](https://github.com/fow5040/Flow.Launcher.Plugin.SpotifyPremium/files/8173739/Logs.zip)

**Comment by Crossbones18** [comment]
> Looked into this - not sure exactly what's going on but I think the new version of Flow probably uses a different .NET runtime or something. I updated flow (`Flow` -> `Check for update`) and the spotify plugin is working fine. Does that resolve the issue?

Excellent! That looks like it did the trick. Thank you for the quick turnaround! Keep up the great work you are doing.
