### ISSUE TITLE
Improvement - better handling of no premium error

### ISSUE THREAD

**Issue by deefrawley** [fow5040/Flow.Launcher.Plugin.SpotifyPremium#7]
Hi,

The main Flow repo gets a lot of issues when people try and use this plugin without a premium Spotify subscription (I know it's right there in the plugin name but many people just see the "Spotify" part and think it will work for all accounts). Can you look at this exception and see if it can be caught and handled in the results window instead? Thanks.

**Comment by fow5040** [comment]
I hadn't considered that - that's something I'd like to add, thank you!

**Comment by fow5040** [comment]
Should be addressed - closing issue and releasing version 1.1.1
